package nl.radiantrealm.enumerator;

public enum AuditType {
    PLAYER_ACCOUNT_CREATE,
    PLAYER_ACCOUNT_UPDATE_NAME,
    SAVINGS_ACCOUNT_CREATE,
    SAVINGS_ACCOUNT_UPDATE_NAME,
    FUNDINGS_ACCOUNT_CREATE,
    FUNDINGS_ACCOUNT_UPDATE_NAME,
}
